server:
  port: 10601
project:
  version: "0.0.1"
spring:
  application:
    name: "products"
  data:
    mongodb:
      database: "products"
      host: "localhost"
      port: 10501
  cloud:
    nacos.discovery.server-addr: "http://localhost:10401"

springdoc:
  swagger-ui:
    use-root-path: true